language: ruby
rvm:
  - 2.1.5
services:
  - postgresql
env:
  - DB=postgresql
  - RAILS_ENV=test
addons:
  postgresql: "9.3"
script:
  - bundle exec rake --trace db:migrate RAILS_ENV=test
before_script:
    - psql -c 'create database rentaldvd_test' -U postgres
    - cp config/database.yml.travis config/database.yml

